#!/usr/bin/env python3

__author__ = ["litmus-ritten"]
__license__ = "MIT"
__description__ = "Constants for slurpy"
__note__ = """Emblemish mappings were originally implemented by ~palfun-foslup and are reproduced here with permission.
Thank you to ~lidreg-dillut for pointing me to them."""

from Rank import Rank

DA_EPOCH = 170141184475152167957503069145530368000
DA_SECOND = 18446744073709551616

EXPECTED_PATP_LEN = [3, 6, 9, 12, 18, 24, 48]

EXPECTED_PATP_SHAPE = {
    "galaxy": r"^~?[a-z]{3}$",
    "star": r"^~?[a-z]{6}$",
    "planet": r"^~?[a-z]{6}-[a-z]{6}$",
    "moon": r"^~?[a-z]{6}-[a-z]{6}-[a-z]{6}-[a-z]{6}$",
    "moon_short": r"^~?[a-z]{6}-[a-z]{6}-[a-z]{6}$",
    "comet": r"^~?[a-z]{6}-[a-z]{6}-[a-z]{6}-[a-z]{6}--[a-z]{6}-[a-z]{6}-[a-z]{6}-[a-z]{6}$",
}


SEIN_RELATIONS = {
    Rank.CZAR: {"galaxy": None, "star": None, "planet": None},
    Rank.KING: {"galaxy": -1, "star": None, "planet": None},
    Rank.DUKE: {"galaxy": -1, "star": -2, "planet": None},
    Rank.EARL: {"galaxy": -1, "star": -2, "planet": -3},
    Rank.PAWN: {"galaxy": -1, "star": None, "planet": None},
}

CLANS = {
    "galaxy": Rank.CZAR,
    "star": Rank.KING,
    "planet": Rank.DUKE,
    "moon": Rank.EARL,
    "comet": Rank.PAWN,
}

CARTOUCHE_SYMBOL = {
    0: "🍄",
    1: "🐢",
    2: "🦜",
    3: "🐱",
    4: "🐙",
    5: "🐐",
    6: "🐶",
    7: "🦌",
    8: "🐝",
    9: "🐛",
    10: "🦦",
    11: "🪼",
    12: "🐨",
    13: "🐰",
    14: "🪴",
    15: "🍀",
}

PATP_SYL = {
    "prefix": {
        "doz": 0,
        "mar": 1,
        "bin": 2,
        "wan": 3,
        "sam": 4,
        "lit": 5,
        "sig": 6,
        "hid": 7,
        "fid": 8,
        "lis": 9,
        "sog": 10,
        "dir": 11,
        "wac": 12,
        "sab": 13,
        "wis": 14,
        "sib": 15,
        "rig": 16,
        "sol": 17,
        "dop": 18,
        "mod": 19,
        "fog": 20,
        "lid": 21,
        "hop": 22,
        "dar": 23,
        "dor": 24,
        "lor": 25,
        "hod": 26,
        "fol": 27,
        "rin": 28,
        "tog": 29,
        "sil": 30,
        "mir": 31,
        "hol": 32,
        "pas": 33,
        "lac": 34,
        "rov": 35,
        "liv": 36,
        "dal": 37,
        "sat": 38,
        "lib": 39,
        "tab": 40,
        "han": 41,
        "tic": 42,
        "pid": 43,
        "tor": 44,
        "bol": 45,
        "fos": 46,
        "dot": 47,
        "los": 48,
        "dil": 49,
        "for": 50,
        "pil": 51,
        "ram": 52,
        "tir": 53,
        "win": 54,
        "tad": 55,
        "bic": 56,
        "dif": 57,
        "roc": 58,
        "wid": 59,
        "bis": 60,
        "das": 61,
        "mid": 62,
        "lop": 63,
        "ril": 64,
        "nar": 65,
        "dap": 66,
        "mol": 67,
        "san": 68,
        "loc": 69,
        "nov": 70,
        "sit": 71,
        "nid": 72,
        "tip": 73,
        "sic": 74,
        "rop": 75,
        "wit": 76,
        "nat": 77,
        "pan": 78,
        "min": 79,
        "rit": 80,
        "pod": 81,
        "mot": 82,
        "tam": 83,
        "tol": 84,
        "sav": 85,
        "pos": 86,
        "nap": 87,
        "nop": 88,
        "som": 89,
        "fin": 90,
        "fon": 91,
        "ban": 92,
        "mor": 93,
        "wor": 94,
        "sip": 95,
        "ron": 96,
        "nor": 97,
        "bot": 98,
        "wic": 99,
        "soc": 100,
        "wat": 101,
        "dol": 102,
        "mag": 103,
        "pic": 104,
        "dav": 105,
        "bid": 106,
        "bal": 107,
        "tim": 108,
        "tas": 109,
        "mal": 110,
        "lig": 111,
        "siv": 112,
        "tag": 113,
        "pad": 114,
        "sal": 115,
        "div": 116,
        "dac": 117,
        "tan": 118,
        "sid": 119,
        "fab": 120,
        "tar": 121,
        "mon": 122,
        "ran": 123,
        "nis": 124,
        "wol": 125,
        "mis": 126,
        "pal": 127,
        "las": 128,
        "dis": 129,
        "map": 130,
        "rab": 131,
        "tob": 132,
        "rol": 133,
        "lat": 134,
        "lon": 135,
        "nod": 136,
        "nav": 137,
        "fig": 138,
        "nom": 139,
        "nib": 140,
        "pag": 141,
        "sop": 142,
        "ral": 143,
        "bil": 144,
        "had": 145,
        "doc": 146,
        "rid": 147,
        "moc": 148,
        "pac": 149,
        "rav": 150,
        "rip": 151,
        "fal": 152,
        "tod": 153,
        "til": 154,
        "tin": 155,
        "hap": 156,
        "mic": 157,
        "fan": 158,
        "pat": 159,
        "tac": 160,
        "lab": 161,
        "mog": 162,
        "sim": 163,
        "son": 164,
        "pin": 165,
        "lom": 166,
        "ric": 167,
        "tap": 168,
        "fir": 169,
        "has": 170,
        "bos": 171,
        "bat": 172,
        "poc": 173,
        "hac": 174,
        "tid": 175,
        "hav": 176,
        "sap": 177,
        "lin": 178,
        "dib": 179,
        "hos": 180,
        "dab": 181,
        "bit": 182,
        "bar": 183,
        "rac": 184,
        "par": 185,
        "lod": 186,
        "dos": 187,
        "bor": 188,
        "toc": 189,
        "hil": 190,
        "mac": 191,
        "tom": 192,
        "dig": 193,
        "fil": 194,
        "fas": 195,
        "mit": 196,
        "hob": 197,
        "har": 198,
        "mig": 199,
        "hin": 200,
        "rad": 201,
        "mas": 202,
        "hal": 203,
        "rag": 204,
        "lag": 205,
        "fad": 206,
        "top": 207,
        "mop": 208,
        "hab": 209,
        "nil": 210,
        "nos": 211,
        "mil": 212,
        "fop": 213,
        "fam": 214,
        "dat": 215,
        "nol": 216,
        "din": 217,
        "hat": 218,
        "nac": 219,
        "ris": 220,
        "fot": 221,
        "rib": 222,
        "hoc": 223,
        "nim": 224,
        "lar": 225,
        "fit": 226,
        "wal": 227,
        "rap": 228,
        "sar": 229,
        "nal": 230,
        "mos": 231,
        "lan": 232,
        "don": 233,
        "dan": 234,
        "lad": 235,
        "dov": 236,
        "riv": 237,
        "bac": 238,
        "pol": 239,
        "lap": 240,
        "tal": 241,
        "pit": 242,
        "nam": 243,
        "bon": 244,
        "ros": 245,
        "ton": 246,
        "fod": 247,
        "pon": 248,
        "sov": 249,
        "noc": 250,
        "sor": 251,
        "lav": 252,
        "mat": 253,
        "mip": 254,
        "fip": 255,
    },
    "suffix": {
        "zod": 0,
        "nec": 1,
        "bud": 2,
        "wes": 3,
        "sev": 4,
        "per": 5,
        "sut": 6,
        "let": 7,
        "ful": 8,
        "pen": 9,
        "syt": 10,
        "dur": 11,
        "wep": 12,
        "ser": 13,
        "wyl": 14,
        "sun": 15,
        "ryp": 16,
        "syx": 17,
        "dyr": 18,
        "nup": 19,
        "heb": 20,
        "peg": 21,
        "lup": 22,
        "dep": 23,
        "dys": 24,
        "put": 25,
        "lug": 26,
        "hec": 27,
        "ryt": 28,
        "tyv": 29,
        "syd": 30,
        "nex": 31,
        "lun": 32,
        "mep": 33,
        "lut": 34,
        "sep": 35,
        "pes": 36,
        "del": 37,
        "sul": 38,
        "ped": 39,
        "tem": 40,
        "led": 41,
        "tul": 42,
        "met": 43,
        "wen": 44,
        "byn": 45,
        "hex": 46,
        "feb": 47,
        "pyl": 48,
        "dul": 49,
        "het": 50,
        "mev": 51,
        "rut": 52,
        "tyl": 53,
        "wyd": 54,
        "tep": 55,
        "bes": 56,
        "dex": 57,
        "sef": 58,
        "wyc": 59,
        "bur": 60,
        "der": 61,
        "nep": 62,
        "pur": 63,
        "rys": 64,
        "reb": 65,
        "den": 66,
        "nut": 67,
        "sub": 68,
        "pet": 69,
        "rul": 70,
        "syn": 71,
        "reg": 72,
        "tyd": 73,
        "sup": 74,
        "sem": 75,
        "wyn": 76,
        "rec": 77,
        "meg": 78,
        "net": 79,
        "sec": 80,
        "mul": 81,
        "nym": 82,
        "tev": 83,
        "web": 84,
        "sum": 85,
        "mut": 86,
        "nyx": 87,
        "rex": 88,
        "teb": 89,
        "fus": 90,
        "hep": 91,
        "ben": 92,
        "mus": 93,
        "wyx": 94,
        "sym": 95,
        "sel": 96,
        "ruc": 97,
        "dec": 98,
        "wex": 99,
        "syr": 100,
        "wet": 101,
        "dyl": 102,
        "myn": 103,
        "mes": 104,
        "det": 105,
        "bet": 106,
        "bel": 107,
        "tux": 108,
        "tug": 109,
        "myr": 110,
        "pel": 111,
        "syp": 112,
        "ter": 113,
        "meb": 114,
        "set": 115,
        "dut": 116,
        "deg": 117,
        "tex": 118,
        "sur": 119,
        "fel": 120,
        "tud": 121,
        "nux": 122,
        "rux": 123,
        "ren": 124,
        "wyt": 125,
        "nub": 126,
        "med": 127,
        "lyt": 128,
        "dus": 129,
        "neb": 130,
        "rum": 131,
        "tyn": 132,
        "seg": 133,
        "lyx": 134,
        "pun": 135,
        "res": 136,
        "red": 137,
        "fun": 138,
        "rev": 139,
        "ref": 140,
        "mec": 141,
        "ted": 142,
        "rus": 143,
        "bex": 144,
        "leb": 145,
        "dux": 146,
        "ryn": 147,
        "num": 148,
        "pyx": 149,
        "ryg": 150,
        "ryx": 151,
        "fep": 152,
        "tyr": 153,
        "tus": 154,
        "tyc": 155,
        "leg": 156,
        "nem": 157,
        "fer": 158,
        "mer": 159,
        "ten": 160,
        "lus": 161,
        "nus": 162,
        "syl": 163,
        "tec": 164,
        "mex": 165,
        "pub": 166,
        "rym": 167,
        "tuc": 168,
        "fyl": 169,
        "lep": 170,
        "deb": 171,
        "ber": 172,
        "mug": 173,
        "hut": 174,
        "tun": 175,
        "byl": 176,
        "sud": 177,
        "pem": 178,
        "dev": 179,
        "lur": 180,
        "def": 181,
        "bus": 182,
        "bep": 183,
        "run": 184,
        "mel": 185,
        "pex": 186,
        "dyt": 187,
        "byt": 188,
        "typ": 189,
        "lev": 190,
        "myl": 191,
        "wed": 192,
        "duc": 193,
        "fur": 194,
        "fex": 195,
        "nul": 196,
        "luc": 197,
        "len": 198,
        "ner": 199,
        "lex": 200,
        "rup": 201,
        "ned": 202,
        "lec": 203,
        "ryd": 204,
        "lyd": 205,
        "fen": 206,
        "wel": 207,
        "nyd": 208,
        "hus": 209,
        "rel": 210,
        "rud": 211,
        "nes": 212,
        "hes": 213,
        "fet": 214,
        "des": 215,
        "ret": 216,
        "dun": 217,
        "ler": 218,
        "nyr": 219,
        "seb": 220,
        "hul": 221,
        "ryl": 222,
        "lud": 223,
        "rem": 224,
        "lys": 225,
        "fyn": 226,
        "wer": 227,
        "ryc": 228,
        "sug": 229,
        "nys": 230,
        "nyl": 231,
        "lyn": 232,
        "dyn": 233,
        "dem": 234,
        "lux": 235,
        "fed": 236,
        "sed": 237,
        "bec": 238,
        "mun": 239,
        "lyr": 240,
        "tes": 241,
        "mud": 242,
        "nyt": 243,
        "byr": 244,
        "sen": 245,
        "weg": 246,
        "fyr": 247,
        "mur": 248,
        "tel": 249,
        "rep": 250,
        "teg": 251,
        "pec": 252,
        "nel": 253,
        "nev": 254,
        "fes": 255,
    },
}

PATP_SYL_REVERSE = {
    "prefix": dict(zip(PATP_SYL["prefix"].values(), PATP_SYL["prefix"].keys())),
    "suffix": dict(zip(PATP_SYL["suffix"].values(), PATP_SYL["suffix"].keys())),
}


EMBLEMISH = {
    "prefix": {
        "doz": {"icon": "⚫", "verb": "the"},
        "mar": {"icon": "1️⃣", "verb": "prime"},
        "bin": {"icon": "🗑", "verb": "discarded"},
        "wan": {"icon": "💕", "verb": "coveted"},
        "sam": {"icon": "👥", "verb": "identical"},
        "lit": {"icon": "🔥", "verb": "impassioned"},
        "sig": {"icon": "🖋", "verb": "contracted"},
        "hid": {"icon": "😶‍🌫️", "verb": "obscure"},
        "fid": {"icon": "🔺", "verb": "greater"},
        "lis": {"icon": "🔻", "verb": "lesser"},
        "sog": {"icon": "💦", "verb": "drenched"},
        "dir": {"icon": "📁", "verb": "collector of"},
        "wac": {"icon": "🤪", "verb": "broken"},
        "sab": {"icon": "✅", "verb": "honest"},
        "wis": {"icon": "🧙‍♂️", "verb": "sage of"},
        "sib": {"icon": "🥷", "verb": "covert"},
        "rig": {"icon": "⛵", "verb": "hoisted"},
        "sol": {"icon": "☀", "verb": "shining"},
        "dop": {"icon": "☕", "verb": "jittery"},
        "mod": {"icon": "💂", "verb": "guardian of"},
        "fog": {"icon": "🌫", "verb": "mysterious"},
        "lid": {"icon": "🧢", "verb": "limited"},
        "hop": {"icon": "🦘", "verb": "kinetic"},
        "dar": {"icon": "🐳", "verb": "distant"},
        "dor": {"icon": "🚪", "verb": "portal to"},
        "lor": {"icon": "📜", "verb": "historied"},
        "hod": {"icon": "🏘", "verb": "collective"},
        "fol": {"icon": "📂", "verb": "amasser of"},
        "rin": {"icon": "💍", "verb": "vowed"},
        "tog": {"icon": "🔮", "verb": "foreseen"},
        "sil": {"icon": "🙃", "verb": "fool's"},
        "mir": {"icon": "🪞", "verb": "parallel"},
        "hol": {"icon": "⛳", "verb": "final"},
        "pas": {"icon": "🛂", "verb": "identifying"},
        "lac": {"icon": "🥛", "verb": "neutral"},
        "rov": {"icon": "🦅", "verb": "roving"},
        "liv": {"icon": "🫒", "verb": "nourishing"},
        "dal": {"icon": "🪙", "verb": "golden"},
        "sat": {"icon": "🛰", "verb": "visionary"},
        "lib": {"icon": "📚", "verb": "documented"},
        "tab": {"icon": "🔖", "verb": "significant"},
        "han": {"icon": "✋", "verb": "dexterous"},
        "tic": {"icon": "🎟", "verb": "admitted"},
        "pid": {"icon": "🦑", "verb": "leviathan"},
        "tor": {"icon": "🧅", "verb": "layered"},
        "bol": {"icon": "🥣", "verb": "vessel for"},
        "fos": {"icon": "🤼", "verb": "antagonist"},
        "dot": {"icon": "🔘", "verb": "instance of"},
        "los": {"icon": "⚰", "verb": "loss of"},
        "dil": {"icon": "🌿", "verb": "savory"},
        "for": {"icon": "🐸", "verb": "fugitive"},
        "pil": {"icon": "💊", "verb": "supposed"},
        "ram": {"icon": "🐏", "verb": "combative"},
        "tir": {"icon": "🐅", "verb": "hidden"},
        "win": {"icon": "🏆", "verb": "triumphant"},
        "tad": {"icon": "🤏", "verb": "miniscule"},
        "bic": {"icon": "🏍", "verb": "roaming"},
        "dif": {"icon": "🆚", "verb": "battling"},
        "roc": {"icon": "🪨", "verb": "rugged"},
        "wid": {"icon": "🌠", "verb": "wishful"},
        "bis": {"icon": "🦬", "verb": "cultivated"},
        "das": {"icon": "🌀", "verb": "turbulent"},
        "mid": {"icon": "💧", "verb": "laminar"},
        "lop": {"icon": "🦞", "verb": "behavioral"},
        "ril": {"icon": "🌄", "verb": "rising"},
        "nar": {"icon": "🧿", "verb": "blinding"},
        "dap": {"icon": "💖", "verb": "handsome"},
        "mol": {"icon": "🌷", "verb": "manic"},
        "san": {"icon": "🎅", "verb": "jolly"},
        "loc": {"icon": "🔒", "verb": "restricted"},
        "nov": {"icon": "🈵", "verb": "occupied"},
        "sit": {"icon": "💩", "verb": "residual"},
        "nid": {"icon": "🧩", "verb": "fragmented"},
        "tip": {"icon": "💵", "verb": "gratuitous"},
        "sic": {"icon": "🤒", "verb": "weakened"},
        "rop": {"icon": "🪳", "verb": "resilient"},
        "wit": {"icon": "🥀", "verb": "expired"},
        "nat": {"icon": "🎁", "verb": "gift of"},
        "pan": {"icon": "🐼", "verb": "endangered"},
        "min": {"icon": "➖", "verb": "absence of"},
        "rit": {"icon": "💥", "verb": "destroyer of"},
        "pod": {"icon": "🐛", "verb": "enslaved"},
        "mot": {"icon": "🦋", "verb": "holometabolic"},
        "tam": {"icon": "™", "verb": "mark of"},
        "tol": {"icon": "🔔", "verb": "herald of"},
        "sav": {"icon": "💾", "verb": "archived"},
        "pos": {"icon": "📯", "verb": "bringer of"},
        "nap": {"icon": "💤", "verb": "slumbering"},
        "nop": {"icon": "🙅", "verb": "declined"},
        "som": {"icon": "🖌", "verb": "painted"},
        "fin": {"icon": "🐬", "verb": "transcendental"},
        "fon": {"icon": "☎", "verb": "networked"},
        "ban": {"icon": "🚫", "verb": "forbidden"},
        "mor": {"icon": "🔁", "verb": "perpetual"},
        "wor": {"icon": "🌍", "verb": "ephemeral"},
        "sip": {"icon": "🥃", "verb": "nursed"},
        "ron": {"icon": "🥚", "verb": "early"},
        "nor": {"icon": "⬆", "verb": "ascendant"},
        "bot": {"icon": "🤖", "verb": "mechanical"},
        "wic": {"icon": "🕯", "verb": "illuminating"},
        "soc": {"icon": "🧦", "verb": "matching"},
        "wat": {"icon": "❓", "verb": "perplexed"},
        "dol": {"icon": "🎎", "verb": "imitation"},
        "mag": {"icon": "🚅", "verb": "expedient"},
        "pic": {"icon": "🖼", "verb": "framed"},
        "dav": {"icon": "🤴", "verb": "king's"},
        "bid": {"icon": "👨‍⚖️", "verb": "offered"},
        "bal": {"icon": "🖲", "verb": "articulated"},
        "tim": {"icon": "🔱", "verb": "triple"},
        "tas": {"icon": "♨", "verb": "boiling"},
        "mal": {"icon": "😈", "verb": "malicious"},
        "lig": {"icon": "✍", "verb": "meticulous"},
        "siv": {"icon": "👁", "verb": "subjective"},
        "tag": {"icon": "🏷", "verb": "marked"},
        "pad": {"icon": "🏠", "verb": "settled"},
        "sal": {"icon": "🧂", "verb": "frustrated"},
        "div": {"icon": "➗", "verb": "separated"},
        "dac": {"icon": "👤", "verb": "shadow of"},
        "tan": {"icon": "🍊", "verb": "citric"},
        "sid": {"icon": "🗣", "verb": "voluble"},
        "fab": {"icon": "🦄", "verb": "flamboyant"},
        "tar": {"icon": "*️⃣", "verb": "surrogate"},
        "mon": {"icon": "🐵", "verb": "simian"},
        "ran": {"icon": "🏃", "verb": "hurried"},
        "nis": {"icon": "❌", "verb": "incongruent"},
        "wol": {"icon": "🦉", "verb": "symbolic"},
        "mis": {"icon": "🎊", "verb": "festive"},
        "pal": {"icon": "🙂", "verb": "friendly"},
        "las": {"icon": "👧", "verb": "youthful"},
        "dis": {"icon": "⛔", "verb": "rejected"},
        "map": {"icon": "🗺", "verb": "guiding"},
        "rab": {"icon": "🐇", "verb": "fertile"},
        "tob": {"icon": "🪃", "verb": "return of"},
        "rol": {"icon": "🌯", "verb": "packaged"},
        "lat": {"icon": "🦤", "verb": "extinct"},
        "lon": {"icon": "🌐", "verb": "longitudinal"},
        "nod": {"icon": "😪", "verb": "exhausted"},
        "nav": {"icon": "➡", "verb": "directional"},
        "fig": {"icon": "🗿", "verb": "monumental"},
        "nom": {"icon": "🍕", "verb": "edible"},
        "nib": {"icon": "⏫", "verb": "improved"},
        "pag": {"icon": "📟", "verb": "indicative"},
        "sop": {"icon": "🧼", "verb": "cleansed"},
        "ral": {"icon": "😎", "verb": "radical"},
        "bil": {"icon": "💶", "verb": "owed"},
        "had": {"icon": "🈹", "verb": "discounted"},
        "doc": {"icon": "🧑‍⚕️", "verb": "shamanic"},
        "rid": {"icon": "🎀", "verb": "giver of"},
        "moc": {"icon": "🦈", "verb": "apex"},
        "pac": {"icon": "🌝", "verb": "ravenous"},
        "rav": {"icon": "☢", "verb": "decaying"},
        "rip": {"icon": "🪦", "verb": "perished"},
        "fal": {"icon": "🍂", "verb": "waning"},
        "tod": {"icon": "👶", "verb": "born"},
        "til": {"icon": "🚜", "verb": "worker of"},
        "tin": {"icon": "🥫", "verb": "preserved"},
        "hap": {"icon": "🐣", "verb": "fledgling"},
        "mic": {"icon": "🎤", "verb": "recorded"},
        "fan": {"icon": "🐘", "verb": "learned"},
        "pat": {"icon": "🌳", "verb": "natural"},
        "tac": {"icon": "📌", "verb": "fastened"},
        "lab": {"icon": "🧪", "verb": "experimental"},
        "mog": {"icon": "💪", "verb": "impressive"},
        "sim": {"icon": "👨‍💼", "verb": "subject to"},
        "son": {"icon": "👨‍👩‍👦", "verb": "heir to"},
        "pin": {"icon": "📍", "verb": "located"},
        "lom": {"icon": "👽", "verb": "demonic"},
        "ric": {"icon": "🦗", "verb": "restless"},
        "tap": {"icon": "🚰", "verb": "dispenser of"},
        "fir": {"icon": "🌲", "verb": "appeal to"},
        "has": {"icon": "📫", "verb": "recipient of"},
        "bos": {"icon": "✝", "verb": "absolute"},
        "bat": {"icon": "🦇", "verb": "echoing"},
        "poc": {"icon": "🆔", "verb": "unique"},
        "hac": {"icon": "🕶", "verb": "background"},
        "tid": {"icon": "🧄", "verb": "potent"},
        "hav": {"icon": "✊", "verb": "grasped"},
        "sap": {"icon": "🩸", "verb": "vital"},
        "lin": {"icon": "🔗", "verb": "attached"},
        "dib": {"icon": "🥇", "verb": "prioritized"},
        "hos": {"icon": "🐎", "verb": "equestrian"},
        "dab": {"icon": "💯", "verb": "maximal"},
        "bit": {"icon": "🫦", "verb": "suggestive"},
        "bar": {"icon": "🍻", "verb": "hospitable"},
        "rac": {"icon": "🦝", "verb": "thieving"},
        "par": {"icon": "🦜", "verb": "talkative"},
        "lod": {"icon": "🔊", "verb": "deafening"},
        "dos": {"icon": "🐫", "verb": "double"},
        "bor": {"icon": "🐗", "verb": "strongwilled"},
        "toc": {"icon": "📑", "verb": "arranged"},
        "hil": {"icon": "⛰", "verb": "unyielding"},
        "mac": {"icon": "🍏", "verb": "newtonian"},
        "tom": {"icon": "🥁", "verb": "rumbling"},
        "dig": {"icon": "🅱", "verb": "daring"},
        "fil": {"icon": "🐡", "verb": "expansive"},
        "fas": {"icon": "👀", "verb": "observed"},
        "mit": {"icon": "🏫", "verb": "scholastic"},
        "hob": {"icon": "🗞", "verb": "punished"},
        "har": {"icon": "🫀", "verb": "rhythmic"},
        "mig": {"icon": "🪄", "verb": "vanishing"},
        "hin": {"icon": "🐈‍⬛", "verb": "unfortunate"},
        "rad": {"icon": "🤙", "verb": "tubular"},
        "mas": {"icon": "🎭", "verb": "masquerading"},
        "hal": {"icon": "🎯", "verb": "particular"},
        "rag": {"icon": "🧻", "verb": "sweeping"},
        "lag": {"icon": "⏳", "verb": "behindhand"},
        "fad": {"icon": "🆕", "verb": "trending"},
        "top": {"icon": "🔝", "verb": "ascended"},
        "mop": {"icon": "🧽", "verb": "retainer of"},
        "hab": {"icon": "🔎", "verb": "seeker of"},
        "nil": {"icon": "0️⃣", "verb": "nullifier of"},
        "nos": {"icon": "👃", "verb": "intuitive"},
        "mil": {"icon": "🌾", "verb": "processor of"},
        "fop": {"icon": "🎰", "verb": "fortuitous"},
        "fam": {"icon": "👨‍👩‍👧‍👦", "verb": "tribal"},
        "dat": {"icon": "💿", "verb": "digitized"},
        "nol": {"icon": "🎞", "verb": "analog"},
        "din": {"icon": "🍲", "verb": "satisfying"},
        "hat": {"icon": "🎩", "verb": "dignified"},
        "nac": {"icon": "🪟", "verb": "transparent"},
        "ris": {"icon": "🧗", "verb": "mounting"},
        "fot": {"icon": "📷", "verb": "captured"},
        "rib": {"icon": "🍖", "verb": "scrumptious"},
        "hoc": {"icon": "🏑", "verb": "competitive"},
        "nim": {"icon": "🪁", "verb": "soaring"},
        "lar": {"icon": "🦙", "verb": "corpulent"},
        "fit": {"icon": "🏋", "verb": "lifter of"},
        "wal": {"icon": "🧱", "verb": "obstructive"},
        "rap": {"icon": "🤬", "verb": "censored"},
        "sar": {"icon": "🪢", "verb": "eclectic"},
        "nal": {"icon": "✨", "verb": "magnificant"},
        "mos": {"icon": "🦟", "verb": "humming"},
        "lan": {"icon": "⛓", "verb": "connected"},
        "don": {"icon": "👕", "verb": "wearer of"},
        "dan": {"icon": "🍡", "verb": "sweetened"},
        "lad": {"icon": "👦", "verb": "junior"},
        "dov": {"icon": "🕊", "verb": "spirit of"},
        "riv": {"icon": "🌊", "verb": "cascading"},
        "bac": {"icon": "🧮", "verb": "adder of"},
        "pol": {"icon": "👮", "verb": "upholder of"},
        "lap": {"icon": "🔂", "verb": "repeated"},
        "tal": {"icon": "⛹", "verb": "towering"},
        "pit": {"icon": "🕳", "verb": "abyssal"},
        "nam": {"icon": "📛", "verb": "named"},
        "bon": {"icon": "🦴", "verb": "skeletal"},
        "ros": {"icon": "🌹", "verb": "passionate"},
        "ton": {"icon": "👅", "verb": "toothsome"},
        "fod": {"icon": "🫕", "verb": "molten"},
        "pon": {"icon": "🐴", "verb": "stout"},
        "sov": {"icon": "🗡", "verb": "wielder of"},
        "noc": {"icon": "🔢", "verb": "executive"},
        "sor": {"icon": "🌪", "verb": "forceful"},
        "lav": {"icon": "🚽", "verb": "sanctuary of"},
        "mat": {"icon": "⚛", "verb": "substantial"},
        "mip": {"icon": "🐁", "verb": "squeaking"},
        "fip": {"icon": "🩴", "verb": "flopping"},
    },
    "suffix": {
        "zod": {"icon": "⚫", "verb": "one"},
        "nec": {"icon": "🐍", "verb": "whisperer"},
        "bud": {"icon": "🌱", "verb": "potentiality"},
        "wes": {"icon": "⬅", "verb": "escape"},
        "sev": {"icon": "💰", "verb": "opulence"},
        "per": {"icon": "🌶", "verb": "spice"},
        "sut": {"icon": "🦸", "verb": "heroism"},
        "let": {"icon": "🚸", "verb": "yielding"},
        "ful": {"icon": "🥛", "verb": "satiety"},
        "pen": {"icon": "✏", "verb": "writing"},
        "syt": {"icon": "🖥", "verb": "presentation"},
        "dur": {"icon": "☠", "verb": "doom"},
        "wep": {"icon": "🦫", "verb": "engineer"},
        "ser": {"icon": "🔀", "verb": "chaos"},
        "wyl": {"icon": "⚙", "verb": "enabler"},
        "sun": {"icon": "🌞", "verb": "exuberance"},
        "ryp": {"icon": "🍌", "verb": "maturity"},
        "syx": {"icon": "🃏", "verb": "wildcard"},
        "dyr": {"icon": "‼", "verb": "cognizance"},
        "nup": {"icon": "🗨", "verb": "shibboleth"},
        "heb": {"icon": "🩸", "verb": "blood"},
        "peg": {"icon": "📌", "verb": "adhesion"},
        "lup": {"icon": "❌", "verb": "denial"},
        "dep": {"icon": "🐕‍🦺", "verb": "assistant"},
        "dys": {"icon": "🎲", "verb": "chance"},
        "put": {"icon": "⛳", "verb": "completion"},
        "lug": {"icon": "🧳", "verb": "possessions"},
        "hec": {"icon": "🪀", "verb": "bandalore"},
        "ryt": {"icon": "➡", "verb": "signifyer"},
        "tyv": {"icon": "🦠", "verb": "disease"},
        "syd": {"icon": "🧬", "verb": "programming"},
        "nex": {"icon": "🔜", "verb": "destiny"},
        "lun": {"icon": "🌝", "verb": "satellite"},
        "mep": {"icon": "✉", "verb": "post"},
        "lut": {"icon": "🧰", "verb": "utility"},
        "sep": {"icon": "↔", "verb": "exchange"},
        "pes": {"icon": "🐟", "verb": "pisces"},
        "del": {"icon": "⚗", "verb": "purifier"},
        "sul": {"icon": "💀", "verb": "expiration"},
        "ped": {"icon": "🚶", "verb": "wandering"},
        "tem": {"icon": "🌡", "verb": "degree"},
        "led": {"icon": "🚥", "verb": "directionality"},
        "tul": {"icon": "🌷", "verb": "aesthete"},
        "met": {"icon": "📐", "verb": "determination"},
        "wen": {"icon": "🕓", "verb": "time"},
        "byn": {"icon": "♾", "verb": "eternities"},
        "hex": {"icon": "🧙‍♀️", "verb": "curse"},
        "feb": {"icon": "🧀", "verb": "fermentation"},
        "pyl": {"icon": "📚", "verb": "chronicles"},
        "dul": {"icon": "☁", "verb": "monotony"},
        "het": {"icon": "🚫", "verb": "limits"},
        "mev": {"icon": "⚖", "verb": "balance"},
        "rut": {"icon": "🔁", "verb": "perpetuity"},
        "tyl": {"icon": "🀄", "verb": "representation"},
        "wyd": {"icon": "🌌", "verb": "space"},
        "tep": {"icon": "🤬", "verb": "expletive"},
        "bes": {"icon": "🏹", "verb": "hunter"},
        "dex": {"icon": "👆", "verb": "pointer"},
        "sef": {"icon": "🤳", "verb": "reflection"},
        "wyc": {"icon": "🧾", "verb": "values"},
        "bur": {"icon": "🖨", "verb": "replication"},
        "der": {"icon": "🦌", "verb": "prey"},
        "nep": {"icon": "📰", "verb": "communique"},
        "pur": {"icon": "🐱", "verb": "feline"},
        "rys": {"icon": "🍚", "verb": "staple"},
        "reb": {"icon": "🐀", "verb": "plague"},
        "den": {"icon": "🍢", "verb": "victuals"},
        "nut": {"icon": "🥜", "verb": "legumes"},
        "sub": {"icon": "➖", "verb": "absence"},
        "pet": {"icon": "🐶", "verb": "companion"},
        "rul": {"icon": "🪧", "verb": "indication"},
        "syn": {"icon": "🌈", "verb": "covenant"},
        "reg": {"icon": "👑", "verb": "sovereign"},
        "tyd": {"icon": "🌊", "verb": "torrent"},
        "sup": {"icon": "🏄", "verb": "shredder"},
        "sem": {"icon": "🎌", "verb": "semaphore"},
        "wyn": {"icon": "🍷", "verb": "vintage"},
        "rec": {"icon": "🔴", "verb": "recording"},
        "meg": {"icon": "🗄", "verb": "database"},
        "net": {"icon": "🌐", "verb": "worlds"},
        "sec": {"icon": "👮", "verb": "safekeeper"},
        "mul": {"icon": "🤔", "verb": "contemplation"},
        "nym": {"icon": "📛", "verb": "nomenclature"},
        "tev": {"icon": "👕", "verb": "garnments"},
        "web": {"icon": "🕸", "verb": "entanglement"},
        "sum": {"icon": "🗃", "verb": "aggregate"},
        "mut": {"icon": "🐕", "verb": "canine"},
        "nyx": {"icon": "❄", "verb": "singleton"},
        "rex": {"icon": "🦖", "verb": "king"},
        "teb": {"icon": "🏰", "verb": "stronghold"},
        "fus": {"icon": "😠", "verb": "confrontation"},
        "hep": {"icon": "❇", "verb": "deliverance"},
        "ben": {"icon": "🕰", "verb": "hour"},
        "mus": {"icon": "🏛", "verb": "antiquity"},
        "wyx": {"icon": "🎯", "verb": "objective"},
        "sym": {"icon": "🦉", "verb": "mystery"},
        "sel": {"icon": "🧂", "verb": "condiment"},
        "ruc": {"icon": "🪆", "verb": "recursion"},
        "dec": {"icon": "⤵", "verb": "reduction"},
        "wex": {"icon": "🗻", "verb": "trial"},
        "syr": {"icon": "⚔", "verb": "knight"},
        "wet": {"icon": "💦", "verb": "immersion"},
        "dyl": {"icon": "✨", "verb": "ideals"},
        "myn": {"icon": "🧠", "verb": "mind"},
        "mes": {"icon": "🔪", "verb": "partitioning"},
        "det": {"icon": "🌳", "verb": "life"},
        "bet": {"icon": "💸", "verb": "speculation"},
        "bel": {"icon": "🔔", "verb": "herald"},
        "tux": {"icon": "🐧", "verb": "kernel"},
        "tug": {"icon": "🫀", "verb": "heart"},
        "myr": {"icon": "🍯", "verb": "ambrosia"},
        "pel": {"icon": "🫑", "verb": "greens"},
        "syp": {"icon": "🤡", "verb": "ridicule"},
        "ter": {"icon": "🎸", "verb": "legend"},
        "meb": {"icon": "👤", "verb": "generalities"},
        "set": {"icon": "🤞", "verb": "hope"},
        "dut": {"icon": "💢", "verb": "pressure"},
        "deg": {"icon": "🍆", "verb": "debauchery"},
        "tex": {"icon": "🤠", "verb": "independence"},
        "sur": {"icon": "🏳", "verb": "surrender"},
        "fel": {"icon": "😡", "verb": "rage"},
        "tud": {"icon": "♠", "verb": "spades"},
        "nux": {"icon": "♥", "verb": "hearts"},
        "rux": {"icon": "♦", "verb": "diamonds"},
        "ren": {"icon": "♣", "verb": "clubs"},
        "wyt": {"icon": "⚪", "verb": "purity"},
        "nub": {"icon": "🔘", "verb": "protrusion"},
        "med": {"icon": "⚕", "verb": "panacea"},
        "lyt": {"icon": "💡", "verb": "radiance"},
        "dus": {"icon": "💨", "verb": "particulates"},
        "neb": {"icon": "🔰", "verb": "beginnings"},
        "rum": {"icon": "🥃", "verb": "spirits"},
        "tyn": {"icon": "🎐", "verb": "tranquility"},
        "seg": {"icon": "🧩", "verb": "segment"},
        "lyx": {"icon": "🐈", "verb": "predator"},
        "pun": {"icon": "⛎", "verb": "meta"},
        "res": {"icon": "🈯", "verb": "reservation"},
        "red": {"icon": "🍎", "verb": "crimson"},
        "fun": {"icon": "😂", "verb": "hysteria"},
        "rev": {"icon": "❤️‍🔥", "verb": "revelation"},
        "ref": {"icon": "🪑", "verb": "furniture"},
        "mec": {"icon": "🩹", "verb": "mending"},
        "ted": {"icon": "🪂", "verb": "thrill"},
        "rus": {"icon": "🐚", "verb": "husk"},
        "bex": {"icon": "♨", "verb": "oracle"},
        "leb": {"icon": "🪵", "verb": "material"},
        "dux": {"icon": "🦆", "verb": "waterfowl"},
        "ryn": {"icon": "🦏", "verb": "panzer"},
        "num": {"icon": "🦬", "verb": "stampede"},
        "pyx": {"icon": "🧚", "verb": "trickster"},
        "ryg": {"icon": "⚡", "verb": "force"},
        "ryx": {"icon": "🐝", "verb": "monarchy"},
        "fep": {"icon": "📴", "verb": "retreat"},
        "tyr": {"icon": "🛞", "verb": "locomotion"},
        "tus": {"icon": "🦣", "verb": "mammoth"},
        "tyc": {"icon": "⚠", "verb": "attention"},
        "leg": {"icon": "🦵", "verb": "support"},
        "nem": {"icon": "🧲", "verb": "attractor"},
        "fer": {"icon": "🌲", "verb": "appeal"},
        "mer": {"icon": "🧜‍♀️", "verb": "amalgam"},
        "ten": {"icon": "🔟", "verb": "decimal"},
        "lus": {"icon": "➕", "verb": "additive"},
        "nus": {"icon": "💭", "verb": "nous"},
        "syl": {"icon": "🗝", "verb": "solution"},
        "tec": {"icon": "💻", "verb": "gateway"},
        "mex": {"icon": "🌮", "verb": "folding"},
        "pub": {"icon": "🍻", "verb": "conviviality"},
        "rym": {"icon": "📝", "verb": "poetry"},
        "tuc": {"icon": "🦃", "verb": "thanksgiving"},
        "fyl": {"icon": "💕", "verb": "lover"},
        "lep": {"icon": "🐆", "verb": "panther"},
        "deb": {"icon": "🤵", "verb": "debonair"},
        "ber": {"icon": "🐻", "verb": "ursid"},
        "mug": {"icon": "🧺", "verb": "container"},
        "hut": {"icon": "🛖", "verb": "compound"},
        "tun": {"icon": "📻", "verb": "attunement"},
        "byl": {"icon": "🤮", "verb": "expeller"},
        "sud": {"icon": "📼", "verb": "excuse"},
        "pem": {"icon": "♟", "verb": "pawn"},
        "dev": {"icon": "👨‍💻", "verb": "conductor"},
        "lur": {"icon": "🎣", "verb": "catch"},
        "def": {"icon": "🙉", "verb": "ignoramus"},
        "bus": {"icon": "🚌", "verb": "carriage"},
        "bep": {"icon": "🔊", "verb": "cacophony"},
        "run": {"icon": "🏃", "verb": "strider"},
        "mel": {"icon": "🫠", "verb": "disarray"},
        "pex": {"icon": "💪", "verb": "strongman"},
        "dyt": {"icon": "🌛", "verb": "crepuscule"},
        "byt": {"icon": "🦈", "verb": "masticator"},
        "typ": {"icon": "⌨", "verb": "translator"},
        "lev": {"icon": "🚅", "verb": "conveyance"},
        "myl": {"icon": "🏎", "verb": "speedster"},
        "wed": {"icon": "🌿", "verb": "herb"},
        "duc": {"icon": "💫", "verb": "vertigo"},
        "fur": {"icon": "🐺", "verb": "anthropomorph"},
        "fex": {"icon": "🧯", "verb": "extinguisher"},
        "nul": {"icon": "0️⃣", "verb": "void"},
        "luc": {"icon": "🍀", "verb": "fortune"},
        "len": {"icon": "📏", "verb": "extent"},
        "ner": {"icon": "🦥", "verb": "sloth"},
        "lex": {"icon": "💬", "verb": "gab"},
        "rup": {"icon": "🥠", "verb": "aphorism"},
        "ned": {"icon": "🇳🇱", "verb": "lowlands"},
        "lec": {"icon": "😈", "verb": "sophistry"},
        "ryd": {"icon": "🏇", "verb": "roughrider"},
        "lyd": {"icon": "☀", "verb": "light"},
        "fen": {"icon": "🪟", "verb": "exposition"},
        "wel": {"icon": "🎻", "verb": "elegance"},
        "nyd": {"icon": "😤", "verb": "accomplishment"},
        "hus": {"icon": "🤫", "verb": "secrecy"},
        "rel": {"icon": "🌋", "verb": "cataclysm"},
        "rud": {"icon": "💃", "verb": "boogaloo"},
        "nes": {"icon": "🕹", "verb": "diversion"},
        "hes": {"icon": "🌬", "verb": "breath"},
        "fet": {"icon": "☣", "verb": "contaminant"},
        "des": {"icon": "👁", "verb": "providence"},
        "ret": {"icon": "🎱", "verb": "outlook"},
        "dun": {"icon": "🏜", "verb": "wasteland"},
        "ler": {"icon": "⏏", "verb": "emission"},
        "nyr": {"icon": "🥄", "verb": "provider"},
        "seb": {"icon": "🏠", "verb": "abode"},
        "hul": {"icon": "🚢", "verb": "vessel"},
        "ryl": {"icon": "🧭", "verb": "exploration"},
        "lud": {"icon": "👴", "verb": "luddite"},
        "rem": {"icon": "🛡", "verb": "protector"},
        "lys": {"icon": "🤥", "verb": "untruths"},
        "fyn": {"icon": "💎", "verb": "rarity"},
        "wer": {"icon": "🌦", "verb": "conditions"},
        "ryc": {"icon": "🗽", "verb": "liberty"},
        "sug": {"icon": "🍬", "verb": "confection"},
        "nys": {"icon": "👍", "verb": "approval"},
        "nyl": {"icon": "🏕", "verb": "conqueror"},
        "lyn": {"icon": "🦁", "verb": "pride"},
        "dyn": {"icon": "🤸", "verb": "dynamism"},
        "dem": {"icon": "🐴", "verb": "democracy"},
        "lux": {"icon": "🔆", "verb": "luminosity"},
        "fed": {"icon": "🕴", "verb": "spook"},
        "sed": {"icon": "🌰", "verb": "genesis"},
        "bec": {"icon": "🥚", "verb": "kiln"},
        "mun": {"icon": "🌚", "verb": "orbit"},
        "lyr": {"icon": "🎶", "verb": "ballad"},
        "tes": {"icon": "🔬", "verb": "examination"},
        "mud": {"icon": "🏍", "verb": "grime"},
        "nyt": {"icon": "🌃", "verb": "eventide"},
        "byr": {"icon": "🧊", "verb": "preservation"},
        "sen": {"icon": "💠", "verb": "principality"},
        "weg": {"icon": "👻", "verb": "possession"},
        "fyr": {"icon": "🔥", "verb": "inferno"},
        "mur": {"icon": "🗿", "verb": "resolve"},
        "tel": {"icon": "☎", "verb": "mediator"},
        "rep": {"icon": "🐘", "verb": "republic"},
        "teg": {"icon": "🔭", "verb": "gaze"},
        "pec": {"icon": "🐦", "verb": "avian"},
        "nel": {"icon": "🤺", "verb": "swashbuckler"},
        "nev": {"icon": "🔱", "verb": "authority"},
        "fes": {"icon": "🎉", "verb": "celebration"},
    },
}
